import { StyleSheet } from 'react-native'
import { colors, fontFamily } from '../theme'
import { DEFAULT_STYLE } from '@/constants/styles'

export const s = StyleSheet.create({
	container: {
		flex: 1,
		padding: 24,
		backgroundColor: colors.light,
	},
	flatList: {
		paddingTop: 10,
		borderColor: '#F2F2F2',
		borderWidth: 2,
		borderRadius: 10,
		width: '100%',
		marginTop: 20,
	},
	left: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 7,
	},
	right: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 5,
	},
	item: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		marginBottom: 10,
		padding: 5,
	},
	avatar: {
		width: 40,
		height: 40,
		borderRadius: 20,
		borderColor: '#F2F2F2',
		borderWidth: 2,
		justifyContent: 'center',
		alignItems: 'center',
	},
	avatarProfile: {
		width: 80,
		height: 80,
		borderRadius: 50,
		borderColor: colors.gray[200],
		borderWidth: 1,
		justifyContent: 'center',
		alignItems: 'center',
		opacity: 0.7,
		backgroundColor: 'rgba(0,0,0,0.90)',
	},
	name: {
		fontSize: 16,
		fontFamily: fontFamily.regular,
		color: colors.gray[500],
		width: '55%',
	},
	inputContainer: {
		flexDirection: 'row',
		alignItems: 'center',
		borderWidth: 1,
		borderRadius: DEFAULT_STYLE.radius,
		height: 45,
		paddingHorizontal: 8,
		marginTop: 20,
		borderColor: colors.gray[400],
	},
	input: {
		fontSize: 15,
		fontFamily: fontFamily.regular,
		flex: 1,
		color: colors.gray[500],
	},
	error: {
		color: colors.red.base,
		fontSize: 13,
		marginTop: 5,
		fontFamily: fontFamily.regular,
		textAlign: 'left',
	},
	containerProfile: {
		flex: 1,
		alignItems: 'center',
		marginTop: 20,
		gap: 10,
	},
	containerOption: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		width: '100%',
		paddingHorizontal: 10,
		paddingVertical: 10,
		borderColor: '#F2F2F2',
		borderWidth: 2,
		borderRadius: 10,
	},
	username: {
		fontFamily: fontFamily.bold,
		fontSize: 18,
	},
	subtitle: {
		fontSize: 14,
		fontFamily: fontFamily.regular,
		color: colors.gray[500],
		marginBottom: 20,
	},
	containerIcon: {
		backgroundColor: '#FFFFFF',
		padding: 10,
		borderRadius: 50,
		justifyContent: 'center',
		alignItems: 'center',
	},
	containerIconImage: {
		backgroundColor: colors.red.base,
		width: 30,
		height: 30,
		borderRadius: 50,
		justifyContent: 'center',
		alignItems: 'center',
		position: 'absolute',
		right: 0,
		bottom: 0,
	},
	description: {
		fontSize: 14,
		fontFamily: fontFamily.regular,
	},
	descriptionModal: {
		fontSize: 16,
		fontFamily: fontFamily.regular,
		color: colors.gray[500],
		marginTop: 30,
		marginBottom: 10,
	},
	label: {
		marginTop: 10,
		fontFamily: fontFamily.semiBold,
		color: colors.gray[500],
	},
	labelModal: {
		fontSize: 14,
		fontFamily: fontFamily.bold,
		marginBottom: -10,
		color: colors.gray[500],
	},
})
